pipeline:
  identifier: snyktest
  name: snyktest
  projectIdentifier: DhrubaCI
  orgIdentifier: default
  tags: {}
  properties:
    ci:
      codebase:
        connectorRef: dhrubaaccountconnector
        repoName: release-test
        build:
          type: branch
          spec:
            branch: main
  stages:
    - stage:
        identifier: SNYK_IMAGE
        type: CI
        name: SNYK_IMAGE
        description: ""
        spec:
          cloneCodebase: true
          execution:
            steps:
              - step:
                  identifier: test
                  type: Run
                  name: test
                  spec:
                    connectorRef: harnesscommunitydocker
                    image: snyk/snyk:docker-latest
                    shell: Sh
                    command: |-
                      snyk config set api= $SNYK_TOKEN
                      snyk code test || true
                    privileged: true
                    envVariables:
                      SNYK_TOKEN: <+secrets.getValue("SNYK_TOKEN")>N")>
              - step:
                  identifier: build_and_push_image_to_docker
                  type: BuildAndPushDockerRegistry
                  name: build and push image to docker
                  spec:
                    connectorRef: harnesscommunitydocker
                    repo: harnesscommunity/test-release
                    tags:
                      - stable
                    dockerfile: Dockerfile
              - step:
                  identifier: scan_dockerfile
                  type: Run
                  name: scan dockerfile
                  spec:
                    shell: Sh
                    command: docker scan harnesscommunity/test-release
              - step:
                  identifier: Container_Test
                  type: Run
                  name: Container Test
                  spec:
                    connectorRef: harnesscommunitydocker
                    image: snyk/snyk:docker-latest
                    shell: Sh
                    command: |-
                      snyk config set api=$SNYK_TOKEN
                      snyk container test harnesscommunity/test-release:stable
                    envVariables:
                      SNYK_TOKEN: <+secrets.getValue("SNYK_TOKEN")>
          platform:
            os: Linux
            arch: Amd64
          runtime:
            type: Cloud
            spec: {}
  variables:
    - name: SNYK_IMAGE
      type: String
      description: ""
      value: snyk/snyk:docker-latest
