pipeline:
  name: snyktest
  identifier: snyktest
  projectIdentifier: DhrubaCI
  orgIdentifier: default
  tags: {}
  properties:
    ci:
      codebase:
        connectorRef: dhrubaaccountconnector
        repoName: release-test
        build: <+input>
  stages:
    - stage:
        name: SNYK_IMAGE
        identifier: SNYK_IMAGE
        description: ""
        type: CI
        spec:
          cloneCodebase: true
          execution:
            steps:
              - step:
                  type: Run
                  name: test
                  identifier: test
                  spec:
                    connectorRef: harnesscommunitydocker
                    image: "snyk/snyk:docker-latest\t"
                    shell: Sh
                    command: |-
                      snyk config set api= $SNYK_TOKEN
                      snyk code test || true
                    privileged: true
                    envVariables:
                      SNYK_TOKEN: <+secrets.getValue("SNYK_TOKEN")>N")>
          platform:
            os: Linux
            arch: Amd64
          runtime:
            type: Cloud
            spec: {}
  variables:
    - name: SNYK_IMAGE
      type: String
      description: ""
      value: snyk/snyk:docker-latest
