pipeline:
  name: test-release-pipeline
  identifier: testreleasepipeline
  projectIdentifier: DhrubaCI
  orgIdentifier: default
  tags: {}
  stages:
    - stage:
        variables:
          - name: SNYK_IMAGE
            type: String
            value: snyk/snyk-cli:1.745.0-maven-3.5.4
          - name: MAVEN_IMAGE
            type: String
            value: maven:3.8.3-openjdk-11-slim
        type: CI
        spec:
          execution:
            steps:
              - parallel:
                  - step:
                      type: Security
                      name: Snyk Test
                      identifier: Snyk_Test
                      spec:
                        privileged: true
                        settings:
                          policy_type: orchestratedScan
                          scan_type: repository
                          product_name: snyk
                          product_config_name: default
                          product_access_token: <+secrets.getValue("org.SNYK_TOKEN")>
                          repository_project: release-test
                          repository_branch: main
                  - step:
                      type: Run
                      name: Snyk Code Test
                      identifier: Snyk_Code_Test
                      spec:
                        connectorRef: account.harnessImage
                        image: <+CI.variables.SNYK_IMAGE>
                        shell: Sh
                        command: |-
                          snyk config set api=$SNYK_TOKEN
                          snyk code test || true
                        privileged: true
                        envVariables:
                          SNYK_TOKEN: <+secrets.getValue("org.SNYK_TOKEN")>
              - step:
                  type: Run
                  name: Build Container
                  identifier: Build_Container
                  spec:
                    connectorRef: account.harnessImage
                    image: docker:dind
                    shell: Sh
                    command: docker build -t harnesscommunity/test-release:<+pipeline.sequenceId> -f Dockerfile.harness .
                    imagePullPolicy: Always
              - step:
                  type: Security
                  name: Snyk Container Scan
                  identifier: Snyk_Container_Scan
                  spec:
                    privileged: true
                    settings:
                      policy_type: orchestratedScan
                      scan_type: container
                      product_name: snyk
                      product_config_name: default
                      container_project: harnesscommunity/test-release
                      container_tag: <+pipeline.sequenceId>
                      container_type: local
                      container_domain: docker.io
                    imagePullPolicy: Always
          cloneCodebase: true
          serviceConfig:
            serviceRef: ""
            serviceDefinition:
              type: Kubernetes
              spec:
                variables: []
          serviceDependencies:
            - identifier: DiND
              name: DiND
              type: Service
              spec:
                connectorRef: account.harnessImage
                image: docker:dind
                privileged: true
                resources:
                  limits:
                    memory: 2.0Gi
                    cpu: "1.0"
          sharedPaths:
            - /var/run
          platform:
            os: Linux
            arch: Amd64
          runtime:
            type: Cloud
            spec: {}
        name: CI
        identifier: CI
  properties:
    ci:
      codebase:
        connectorRef: dhrubaaccountconnector
        repoName: release-test
        build: <+input>
