pipeline:
  name: test-release-pipeline
  identifier: testreleasepipeline
  projectIdentifier: DhrubaCI
  orgIdentifier: default
  tags: {}
  properties:
    ci:
      codebase:
        connectorRef: dhrubaaccountconnector
        repoName: release-test
        build: <+input>
  stages:
    - stage:
        name: Builds
        identifier: Builds
        description: ""
        type: CI
        spec:
          cloneCodebase: true
          platform:
            os: Linux
            arch: Amd64
          runtime:
            type: Cloud
            spec: {}
          execution:
            steps:
              - step:
                  type: Run
                  name: Install Docker buildx dependencies
                  identifier: Install_Docker_buildx_dependencies
                  spec:
                    shell: Sh
                    command: |-
                      sudo apt-get update
                      sudo apt-get install -y qemu-user-static binfmt-support
              - step:
                  type: Plugin
                  name: Scan docker image
                  identifier: Scan_docker_image
                  spec:
                    connectorRef: harnesscommunitydocker
                    image: harnesscommunity/test-release
                    privileged: true
              - step:
                  type: Run
                  name: Install Docker Scan
                  identifier: Install_Docker_Scan
                  spec:
                    shell: Sh
                    command: |-
                      apt-get update && apt-get install docker-scan-plugin
                      docker scan --accept-license --version
              - step:
                  type: Run
                  name: Run scans
                  identifier: Run_scans
                  spec:
                    shell: Sh
                    command: docker scan --file Dockerfile docker-scan:e2e
              - step:
                  type: BuildAndPushDockerRegistry
                  name: Build and Push an image to Docker Registry
                  identifier: BuildandPushanimagetoDockerRegistry
                  spec:
                    connectorRef: harnesscommunitydocker
                    repo: harnesscommunity/test-release
                    tags:
                      - latest
                    dockerfile: Dockerfile
