pipeline:
  name: test-trivy-scan
  identifier: testtrivyscan
  projectIdentifier: NgLabs
  orgIdentifier: default
  tags: {}
  properties:
    ci:
      codebase:
        connectorRef: gitconnectordhruba
        repoName: release-test
        build: <+input>
  stages:
    - stage:
        name: Trivy Scan
        identifier: Trivy_Scan
        description: ""
        type: CI
        spec:
          cloneCodebase: true
          platform:
            os: Linux
            arch: Amd64
          runtime:
            type: Cloud
            spec: {}
          execution:
            steps:
              - step:
                  type: Run
                  name: runTrivyScan
                  identifier: runTrivyScan
                  spec:
                    shell: Sh
                    command: |-
                      apt-get update -y  
                      apt-get install wget apt-transport-https gnupg lsb-release -y  
                      wget -qO - https://aquasecurity.github.io/trivy-repo/deb/public.key | apt-key add -  
                      echo deb https://aquasecurity.github.io/trivy-repo/deb $(lsb_release -sc) main | tee -a /etc/apt/sources.list.d/trivy.list  
                      apt-get update -y  
                      apt-get install trivy -y  
                      trivy -v  
                      trivy -q image --timeout 20m -f json -o /shared/customer_artifacts/aqua.json redhat/ubi8-minimal:latest  
              - step:
                  type: Security
                  name: "test trivy "
                  identifier: test_trivy
                  spec:
                    privileged: true
                    settings:
                      policy_type: orchestratedScan
                      scan_type: container
                      product_name: aqua-trivy
                      product_config_name: aqua-trivy
                      container_type: docker_v2
                      container_domain: docker.io
                      container_project: harnesscommunity/test-release
                      container_tag: latest
                    imagePullPolicy: Always
