pipeline:
  name: test-trivy-scan
  identifier: testtrivyscan
  projectIdentifier: NgLabs
  orgIdentifier: default
  tags: {}
  properties:
    ci:
      codebase:
        connectorRef: gitconnectordhruba
        repoName: release-test
        build: <+input>
  stages:
    - stage:
        name: Trivy Scan
        identifier: Trivy_Scan
        type: CI
        spec:
          cloneCodebase: true
          platform:
            os: Linux
            arch: Amd64
          runtime:
            type: Cloud
            spec: {}
          execution:
            steps:
              - step:
                  type: Security
                  name: "test trivy "
                  identifier: test_trivy
                  spec:
                    privileged: true
                    settings:
                      policy_type: orchestratedScan
                      scan_type: container
                      product_name: aqua-trivy
                      product_config_name: aqua-trivy
                      container_type: docker_v2
                      container_domain: docker.io
                      container_project: harnesscommunity/test-release
                      container_tag: latest
                    imagePullPolicy: Always
              - step:
                  type: BuildAndPushDockerRegistry
                  name: Build and Push an image to Docker Registry_1
                  identifier: BuildandPushanimagetoDockerRegistry_1
                  spec:
                    connectorRef: harnessdocker
                    repo: test-release
                    tags:
                      - latest
